# Use the official MySQl image as the base image
FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=test_root
ENV MYSQL_DATABASE=app_db
ENV MYSQL_USER=db_user
ENV MYSQL_PASSWORD=test_user

# Expose the MySQL port
EXPOSE 3306
