# Generated by Django 4.2.6 on 2023-11-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="project name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="project description",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#0067c0", max_length=150, verbose_name="color code"
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="project 활성화 여부")),
            ],
            options={
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="ProjectTaskAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_association",
                        to="projects.project",
                        verbose_name="related project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_association",
                        to="tasks.task",
                        verbose_name="related task",
                    ),
                ),
            ],
            options={
                "db_table": "project_task_associations",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="tasks",
            field=models.ManyToManyField(
                related_name="projects",
                through="projects.ProjectTaskAssociation",
                to="tasks.task",
                verbose_name="related tasks",
            ),
        ),
    ]
