# Generated by Django 4.2.6 on 2024-01-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="project name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="project description",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#0067c0", max_length=150, verbose_name="color code"
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="project 활성화 여부")),
            ],
            options={
                "db_table": "projects",
            },
        ),
    ]
