# Generated by Django 4.2.6 on 2024-01-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pomodoro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "pomodoro_length",
                    models.IntegerField(
                        default=25, verbose_name="pomodoro time length"
                    ),
                ),
                (
                    "break_length",
                    models.IntegerField(default=5, verbose_name="break time length"),
                ),
            ],
            options={
                "db_table": "pomodoros",
            },
        ),
    ]
