# Generated by Django 4.2.6 on 2024-01-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        ("pomodoros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pomodoro",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pomodoros",
                to="tasks.task",
                verbose_name="related task",
            ),
        ),
    ]
